#!/usr/bin/env bash

task_number=${1}
consume_input=${2}

progname=$(basename ${0})
newline="\n"
linefeed=$'\n'
consume_arg="-"
output=""
pipe_editor="vipe"

usage() {
  echo "Usage: ${progname} <task_id>

Edit multiline taskwarrior notes in vi/vim.

Setup a 'notes' UDA for taskwarrior:
  task config uda.notes.type string
  task config uda.notes.label Notes

Notes can also be piped to standard in:

  echo \"foo\" | ${progname} <task_id> -

CAVEATS:

OneNote depends on the vipe pipe editor being installed and in your path.
"
}


# Override the system task binary and pipe editor in testing env.
if [ -n "${ONENOTE_TEST_HARNESS}" ]; then
  pipe_editor="cat"
  task() {
    if [ "${1}" = "_get" ]; then
      echo "${ONENOTE_TEST_NOTES}"
    elif [ "${1}" = "_config" ]; then
      if [ -n "${ONENOTE_MISSING_NOTES}" ]; then
        echo ""
      else
        echo "uda.notes.label\nuda.notes.type"
      fi
    else
      local notes="${3}"
      echo "${notes:6}"
    fi
  }
fi

if [ "$(which vipe)" = "" ]; then
  echo
  echo "ERROR: The vipe binary must be installed and in your path!"
  echo "  see https://joeyh.name/code/moreutils"
  echo
  usage
  exit 1
fi

if [ $# -lt 1 ] || [ $# -gt 2 ]; then
  usage
  exit 1
else
  if [ $# -eq 2 ]; then
    if [ "${2}" != "${consume_arg}" ]; then
      usage
      exit 1
    else
      while IFS='$\n' read -r line; do
        if [ -z "${output}" ]; then
          output="${line}"
        else
          output="${output}${newline}${line}"
        fi
      done
      task ${task_number} modify notes:"${output}"
    fi
  else
    if [ "$(task _config | grep 'uda.notes.type')" = "" ] || [ "$(task _config | grep 'uda.notes.label')" = "" ]; then
      usage
      exit 1
    fi
    notes=$(task _get ${task_number}.notes)
    if [ $? -eq 0 ]; then
      # The literal line feed is necessary for POSIX compatibility with sed.
      echo "${notes}" | ${pipe_editor} | ${0} ${task_number} ${consume_arg}
    fi
  fi
fi
